// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/handle.ts";
import * as $1 from "./routes/api/user.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/user/[id].tsx";
import * as $4 from "./routes/users.tsx";
import * as $$0 from "./islands/UserHandleRow.tsx";

const manifest = {
  routes: {
    "./routes/api/handle.ts": $0,
    "./routes/api/user.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/user/[id].tsx": $3,
    "./routes/users.tsx": $4,
  },
  islands: {
    "./islands/UserHandleRow.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
